import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {AiFillTwitterCircle, AiFillGithub, AiFillLinkedin} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";

export default function Home() {
  return (
    <div>
    <Head>
    <title>Harsham Latif Portfolio</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

    <main className="bg-white px-10 ">
  <section className="min-h-screen">
    <nav className="py-10 mb-12 flex justify-between">
      <h1 className="text-xl font-burtons">Developed by Harsham</h1>
      <ul className="flex items-center">
        <li>
          <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
        </li>
        <li>
          <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">LinkedIn</a>
        </li>
      </ul>
    </nav>
    
    <div className="text-center p-10">
      <h2 className="text-5xl py-2 text-teal-600 font-medium">Harsham Latif</h2>
      <h3 className="text-2xl py-2">Software Developer</h3>
      <p className="text-md py-5 leading-8 text-gray-800">After completing the 16-week intensive School of Code Full Stack Development bootcamp, I am ready to get stuck into the tech industry and grow until my fingers can't move any more!</p>
    </div>
    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
      <AiFillTwitterCircle />
      <AiFillGithub />
      <AiFillLinkedin />
      </div>
    </section>
    </main>
    </div>
  );
}
